In [3]:
from sklearn import datasets
import linear_models.softmaxreg as softmaxreg
import umap
import matplotlib.pyplot as plt
import numpy as np
import metrics.metrics as metrics

In [4]:
iris = datasets.load_iris()
X = iris.data
y = iris.target
 
 
# Split the data into training/testing sets
# training  80% testing 20%
n = X.shape[0]
n_test = int(np.rint(0.2 * n)) 
 
# random sort
idx = np.random.permutation(n)
X = X[idx, :] 
y = y[idx]
 
X_train = X[:-n_test, :]
y_train = y[:-n_test]
 
X_test = X[-n_test:,:]
y_test = y[-n_test:]


""" data normalization, improve convergence """
#"X_Train 150 x4 d = 4
#"mu es un vector de tamaño 4
#"dst es un vector de tamaño 4 
mu = np.mean(X_train, axis = 0)
dst = np.std(X_train, axis = 0)
X_train = (X_train - mu) / dst
X_test = (X_test - mu) / dst
"""-------------------------------------------"""
 
SM = softmaxreg.SoftmaxReg(3)
coeff = SM.fit(X_train, y_train)
""" prediction on test """
y_pred = SM.predict(X_test)
acc = metrics.multiclass_accuracy(y_test, y_pred)
print('acc {}'.format(acc))
#  
# # show confusion matrix
# print(y_pred.shape)
# print(y_test.shape)
cm = metrics.confusion_matrix(y_test, y_pred, 3)

print('confusion matrix')
print(cm)
#  
# # Just data visualization
# #  #project 2D
# # reducer = umap.UMAP()
# # print('UMAP', flush = True)
# # reducer.fit(X) 
# # embedding = reducer.transform(X)
# # print(embedding.shape)
# # plt.scatter(embedding[:, 0], embedding[:, 1], c=y, cmap='Paired') 
# # plt.show()

it 0 acc 0.4
it 10 acc 0.48333333333333334
it 20 acc 0.7916666666666666
it 30 acc 0.8333333333333334
it 40 acc 0.8333333333333334
it 50 acc 0.8333333333333334
it 60 acc 0.8166666666666667
it 70 acc 0.825
it 80 acc 0.8416666666666667
it 90 acc 0.85
it 100 acc 0.85
it 110 acc 0.8583333333333333
it 120 acc 0.85
it 130 acc 0.8416666666666667
it 140 acc 0.8416666666666667
it 150 acc 0.8416666666666667
it 160 acc 0.8416666666666667
it 170 acc 0.8416666666666667
it 180 acc 0.8333333333333334
it 190 acc 0.8333333333333334
acc 0.9
confusion matrix
[[12  0  0]
 [ 0  6  3]
 [ 0  0  9]]
