IMPORTS BEFORE RUNNING CODE BELOW

In [1]:
import tensorflow.keras.datasets as datasets
import matplotlib.pyplot as plt
import numpy as np
from skimage.feature import hog
import linear_models.softmaxreg as softmaxreg
import umap
import matplotlib.pyplot as plt
import numpy as np
import metrics.metrics as metrics

2023-04-09 01:01:11.322843: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
2023-04-09 01:01:14.273484: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
2023-04-09 01:01:14.354900: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX512F FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-04-09 01:01:22.526385: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
/home/codespace/.python/current/lib/python3.10/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


TRAINING MODEL USING THE IMAGES

In [2]:
(x_train, y_train), (x_test, y_test) = datasets.mnist.load_data()
print ('{} {}'.format(x_train.shape, x_train.dtype))
print ('{} {}'.format(x_test.shape, x_train.dtype))
digit = x_train[0,:,:]
print(digit.shape)

(60000, 28, 28) uint8
(10000, 28, 28) uint8
(28, 28)


In [3]:
SM = softmaxreg.SoftmaxReg(10)

In [4]:
x_train_d_784 = x_train.reshape(60000,-1)
x_test_d_784 = x_test.reshape(10000,-1)

In [5]:
coeff = SM.fit(x_train_d_784, y_train)

it 0 acc 0.09745
it 10 acc 0.6152666666666666
it 20 acc 0.8533333333333334
it 30 acc 0.8775
it 40 acc 0.7221333333333333
it 50 acc 0.8900666666666667
it 60 acc 0.7564166666666666
it 70 acc 0.74095
it 80 acc 0.8870833333333333
it 90 acc 0.9018166666666667
it 100 acc 0.9048
it 110 acc 0.7024833333333333
it 120 acc 0.85215
it 130 acc 0.90595
it 140 acc 0.9106166666666666
it 150 acc 0.90235
it 160 acc 0.81025
it 170 acc 0.7957666666666666
it 180 acc 0.89875
it 190 acc 0.9115833333333333


In [6]:
y_pred = SM.predict(x_test_d_784)

In [7]:
acc = metrics.multiclass_accuracy(y_test, y_pred)
print(f"Accuracy: {acc}")

Accuracy: 0.9116


In [8]:
cm = metrics.confusion_matrix(y_test, y_pred, 10)
print(f'Confusion Matrix\n{cm}')

Confusion Matrix
[[ 954    0    3    3    0    4    7    4    4    1]
 [   0 1098    6    3    0    1    3    2   22    0]
 [   9    8  910   18   10    2   10   11   48    6]
 [   2    0   18  914    0   25    4    9   31    7]
 [   3    2    5    2  894    0   12    3   21   40]
 [  10    1    5   42    9  729   16    7   66    7]
 [  12    2    8    1   14   14  899    3    5    0]
 [   1    6   24   13    7    0    0  943    5   29]
 [   5    6    4   21    9   19    7   12  890    1]
 [   9    4    2    9   37    6    0   33   24  885]]


TRAINING MODEL USING HOG FUNCTION

In [9]:
(x_train, y_train), (x_test, y_test) = datasets.mnist.load_data()
print ('{} {}'.format(x_train.shape, x_train.dtype))
print ('{} {}'.format(x_test.shape, x_train.dtype))
digit = x_train[0,:,:]
print(digit.shape)

(60000, 28, 28) uint8
(10000, 28, 28) uint8
(28, 28)


In [10]:
SM = softmaxreg.SoftmaxReg(10)

In [11]:
x_train_hog = list()
for n in range(len(x_train)):
    digit = x_train[n,:,:]
    fd, hog_image = hog(digit, orientations=8, pixels_per_cell=(7,7), cells_per_block=(1, 1), visualize=True)
    x_train_hog.append(fd)
    if(n%9999 == 0): print(f"{round(n/len(x_train)*100)}%")
x_train_hog = np.array(x_train_hog)

0%
17%
33%
50%
67%
83%
100%


In [12]:
x_test_hog = list()
for n in range(len(x_test)):
    digit = x_test[n,:,:]
    fd, hog_image = hog(digit, orientations=8, pixels_per_cell=(7,7), cells_per_block=(1, 1), visualize=True)
    x_test_hog.append(fd)
    if(n%999 == 0): print(f"{round(n/len(x_test)*100)}%")
x_test_hog = np.array(x_test_hog)

0%
10%
20%
30%
40%
50%
60%
70%
80%
90%
100%


In [13]:
coeff = SM.fit(x_train_hog, y_train)
y_pred = SM.predict(x_test_hog)

it 0 acc 0.10541666666666667
it 10 acc 0.11275
it 20 acc 0.11976666666666666
it 30 acc 0.1274
it 40 acc 0.1356
it 50 acc 0.14355
it 60 acc 0.15131666666666665
it 70 acc 0.15956666666666666
it 80 acc 0.16798333333333335
it 90 acc 0.1771
it 100 acc 0.18638333333333335
it 110 acc 0.19646666666666668
it 120 acc 0.20525
it 130 acc 0.2154
it 140 acc 0.22543333333333335
it 150 acc 0.23526666666666668
it 160 acc 0.24613333333333334
it 170 acc 0.25726666666666664
it 180 acc 0.2675666666666667
it 190 acc 0.27905


In [14]:
acc = metrics.multiclass_accuracy(y_test, y_pred)
print(f"Accuracy: {acc}")

Accuracy: 0.285


In [15]:
cm = metrics.confusion_matrix(y_test, y_pred, 10)
print(f'Confusion Matrix\n{cm}')

Confusion Matrix
[[255   0 333 127   5  14  50   8  74 114]
 [126  61   2  46 156  11 157 402 167   7]
 [234   5 242 314   7  18  68  10 118  16]
 [225   1  82 553  25  18  48   5  40  13]
 [205  11  15  32 282  37  43 128  37 192]
 [116   4  54 227  33  69  91  16 200  82]
 [392   4  59  93   1  51 292   3  10  53]
 [ 41  46 163  22 133   1  65 338 152  67]
 [ 30  13  86 198  31  53  75  24 416  48]
 [ 28   3  34  32 233   6  21 187 123 342]]
